import mongoose from 'mongoose';

const userSchema = new mongoose.Schema(
  {
    username: { type: String, required: true, unique: true, lowercase: true, trim: true },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    passwordHash: String,
    status: { type: String, enum: ['active', 'blocked', 'deleted'], default: 'active' },
    followersCount: { type: Number, default: 0 },
    followingCount: { type: Number, default: 0 },
    displayName: String,
    phone: String,
    bio: String,
    website: String,
    country: String,
    city: String,
    language: { type: String, default: 'en' },
    gender: { type: String, enum: ['male', 'female', 'unspecified', ''], default: '' },
    birthDate: Date,
    avatarUrl: String,
    coverUrl: String,
    emailVerified: { type: Boolean, default: false },
    phoneVerified: { type: Boolean, default: false },
    twoFactorEnabled: { type: Boolean, default: false },
    isPrivateAccount: { type: Boolean, default: false },
    lastActiveAt: Date,
    postsCount: { type: Number, default: 0 },
    reelsCount: { type: Number, default: 0 },
    storiesCount: { type: Number, default: 0 },
    likesReceivedCount: { type: Number, default: 0 },
    reportsAgainstCount: { type: Number, default: 0 },
    strikesCount: { type: Number, default: 0 },
    riskScore: { type: Number, default: 0 },
    creatorProgram: { type: Boolean, default: false },
    walletBalance: { type: Number, default: 0 },
    walletCurrency: { type: String, default: 'INR' },
    signupSource: { type: String, default: 'organic' },
    deviceLast: String,
    ipCountry: String,
    referralCode: String,
    adminNotes: String,
  },
  { timestamps: true }
);

export const User = mongoose.model('User', userSchema);
